name: PhotoTest
favicon: null
layout_spectrum: 0.09294601762667298
typography_spectrum: 0.3268038029782474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5963672385551035
  lightness: 0.3637513713911176
  saturation: 0.7692807333078235
  rhythmicContrast: 0.0059435858856886625
purpose: []
