name: PhotoTest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f4eb'
    - '#7280a3'
    - '#b6c0cc'
    - '#08090d'
    - '#3e4e68'
  brandStrength: 0.5963672385551035
  lightness: 0.3637513713911176
  saturation: 0.7692807333078235
  rhythmicContrast: 0.0059435858856886625
purpose: []
